[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[functions]
  directory = "src"
  node_bundler = "esbuild"
  external_node_modules = []

[[redirects]]
  from = "/"
  to = "./netlify/functions/index"
  status = 200